apiVersion: batch/v1
kind: Job
metadata: { name: fraud-detection } # Corrected metadata syntax
spec:
  template:
    spec:
      serviceAccountName: ai-sa # This should match the SA created by Terraform for the ai-jobs namespace
      restartPolicy: Never
      containers:
      - name: fraud-detection
        image: placeholder
        resources: { # This block is required by your Kyverno policy
            requests: {
                memory: 64Mi,
                cpu: 50m
            },
            limits: {
                memory: 128Mi,
                cpu: 100m
            }
        }
        env:
        - { name: RABBITMQ_HOST, value: rabbitmq.messaging.svc.cluster.local }
        volumeMounts:
        - { name: artifacts, mountPath: /artifacts }
      volumes:
      - name: artifacts
        persistentVolumeClaim: { claimName: model-artifacts }