resources:
- job.yaml
images:
- name: placeholder
  newName: docker.io/k18sc01/fraud-detection
  newTag: ea2003b25d7c54765ef21f5688480297018dcb3b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
