apiVersion: apps/v1
kind: Deployment # Keeping this for multi-pod deployment.
metadata: 
  name: hello-app # Name of the deployment object
  labels: 
    app: hello-app
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: hello-app
  template: 
    metadata: 
      labels: 
        app: hello-app
    spec:
      containers: 
      - name: hello-app
        image: nginxdemos/hello:plain-text
        ports: 
        - containerPort: 80

---
apiVersion: v1 
kind: Service 
metadata: 
  name: hello-app
  labels: 
    app: hello-app
spec: 
  type: ClusterIP # Explicitly declare the service type (default)
  selector: 
    app: hello-app
  ports: 
  - port: 80
    targetPort: 80
