apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec: 
  project: default 
  source: 
    repoURL: https://github.com/ShrutiC-git/self-service-with-argo.git
    targetRevision: main
    path: workloads/messaging
  destination: 
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true